version: '3'

services:
  api:
    image: node:lts
    command: yarn dev:server
    depends_on:
      - sqldb
    ports:
      - '3333:3333'
    user: node
    working_dir: /home/node/api
    volumes:
      - ./:/home/node/api
    networks:
      - api_net

  sqldb:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - /tmp/pgdata:/bitnami/postgresql
    networks:
      - api_net
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gobarber

networks:
  api_net:
    driver: bridge
