version: '3'

services:
  api:
    image: node:lts
    command: yarn dev:server
    depends_on:
      - sqldb
      - mongodb
    ports:
      - '3333:3333'
    user: node
    working_dir: /home/node/api
    volumes:
      - ./:/home/node/api
    networks:
      - api_net

  sqldb:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/pgsql:/bitnami/postgresql
    networks:
      - api_net
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gobarber

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
    volumes:
      - /var/lib/mongodb:/bitnami/mongodb
    networks:
      - api_net
    environment:
      - MONGODB_ROOT_PASSWORD=mongobarber

networks:
  api_net:
    driver: bridge
