version: '3'

services:
  api:
    image: node:lts
    user: node
    working_dir: /home/node/api
    ports:
      - 3333:3333
    volumes:
      - ./:/home/node/api
    networks:
      - api-net
    depends_on:
      - postgresdb
    command: yarn dev:server

  postgresdb:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgres
    networks:
      - api-net
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gobarber

networks:
  api-net:
    driver: bridge
volumes:
  postgres_data:
